export const ACTION_TYPE = {
	SET_TODOS: 'SET_TODOS',
	ADD_TODO: 'ADD_TODO',
	REMOVE_TODO: 'REMOVE_TODO',
	UPDATE_TITLE_TODO: 'UPDATE_TITLE_TODO',
	COMPLETED_TODO: 'COMPLETED_TODO',
	LOADING_START: 'LOADING_START',
	LOADING_END: 'LOADING_END',
	SET_IS_SORTED: 'SET_IS_SORTED',
	SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
};
